Update Pester.yml

diff --git a/.github/workflows/Pester.yml b/.github/workflows/Pester.yml
--- a/.github/workflows/Pester.yml
+++ b/.github/workflows/Pester.yml
@@ -1,15 +1,32 @@
 name: Pester
 on:
-  push:
+  pull_request:
     branches: [ main ]
 jobs:
   test-pwsh:
-    runs-on: windows-latest
+    strategy:
+      matrix:
+        platform: [ubuntu-latest, macos-latest, windows-latest]
+    runs-on: ${{ matrix.platform }}
     steps:
     - uses: actions/checkout@v3
-    - name: Run Pester tests
+    - name: Run Pester tests (pwsh)
       run: |
+        Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
         Set-PSRepository psgallery -InstallationPolicy trusted
-        Install-Module -Name Pester -RequiredVersion 5.0.4 -Confirm:$false -Force
+        Install-Module -Name Pester -RequiredVersion 5.0.4 -confirm:$false -Force
         Invoke-Pester -Path "tests"        
       shell: pwsh
+  
+  test-posh:
+    runs-on: windows-latest
+    steps:
+    - uses: actions/checkout@v2
+    - name: Run Pester tests (PowerShell)
+      run: |
+        Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
+        Set-PSRepository psgallery -InstallationPolicy trusted
+        Install-Module -Name Pester -RequiredVersion 5.0.4 -Confirm:$false -Force
+        Invoke-Pester -Path "tests"
+        if ($Error[0].Fullyqualifiederrorid -eq 'PesterAssertionFailed') {exit 1}        
+      shell: powershell
